name: Demo push with tags
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Lokalise
        uses: bodrovis/lokalise-push-action@locales_folders_list
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 4802394962963e6990a4e5.99847316
          base_lang: en
          translations_path: |
            local
            i18n
          file_format: json
          additional_params: "--convert-placeholders --hidden-from-contributors"
